# ===========================================
# Mosquitto MQTT Broker ?????????
# ===========================================
listener 1883
protocol mqtt
listener 9001
protocol websockets
allow_anonymous false
password_file /mosquitto/data/passwd
acl_file /mosquitto/data/acl
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type all
log_timestamp true
connection_messages true
